
- name: Configure Loopback Interface
  hosts: cisco
  gather_facts: false

  tasks:

    - name: Configure Loopback100
      cisco.ios.ios_config:
        parents: interface Loopback100
        lines:
          - ip address 100.100.100.1 255.255.255.255
          - description Configured-by-Ansible
          - no shutdown
