---
- name: Run Show Commands
  hosts: cisco
  gather_facts: false

  tasks:

    - name: Show Version
      cisco.ios.ios_command:
        commands:
          - show version
          - show ip interface brief
          - show running-config
      register: output

    - name: Display Output
      debug:
        var: output.stdout_lines
