---
- name: Save output
  hosts: cisco
  gather_facts: false

  tasks:

    - name: Show interfaces
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interfaces

    - name: Display output
      debug:
        var: interfaces.stdout_lines
